### ISSUE TITLE
Adicionar link para call4papers

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#106]
https://www.papercall.io/reactconfbr2018

**Comment by danielGalvao** [comment]
Done! #107

**Comment by MathMesquita** [comment]
The URL is Broken... was it supposed to happen?

**Comment by danielGalvao** [comment]
Ok for me! No problem here...

**Comment by danielGalvao** [comment]
![captura de tela 2018-07-17 as 18 07 35](https://user-images.githubusercontent.com/5161645/42845461-62d80550-89ec-11e8-9cf5-604b69003e50.png)
