### ISSUE TITLE
Adicionar Smartlook site React Conf BR

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#11]
Smartlook - Ferramenta Gratuita de Gravação de Tela e Repetição de Sessão do Visitante
<https://www.smartlook.com/pt/>

Sugestão: @ronal2do

**Comment by rodrigooler** [comment]
@danvitoriano precisa criar uma conta para ter acesso ao smartlook para efetuar a geração do script para colocar no public/index.html

**Comment by danvitoriano** [comment]
conseguiu criar a conta @rodrigooler 
vc vai ficar mesmo com essa issue?
assume ela aqui!

**Comment by rodrigooler** [comment]
Issue resolved https://github.com/react-brasil/conf/pull/23.
