### ISSUE TITLE
Adicionar Stage Now ao site React Conf BR

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#12]
Para criar um ambiente de staging, assim podemos ver alterações na página antes de subir pro ar.
<https://stage.now.sh/>

Sugestão de @lucasbento

**Comment by jvcjunior** [comment]
@danvitoriano posso pegar essa? Gostaria de aprender a fazer isso e ver como esse now funciona. Que tal?

**Comment by jvcjunior** [comment]
Galera, consegui subir uma versão:
https://reactconf-rhscquawpk.now.sh/

Só que percebi que são necessários alguns passos e preciso saber o que dizem sobre. Por exemplo, é necessário criar uma conta nesse site https://zeit.co. 

Além disso, é necessário criar um webhook no repositório. Coisa que não dá para eu "repassar" via um pull-request acredito eu. Então, acho que essas configurações devem ser feitas no próprio repositório da conferência. 

É necessário criar um personal access token. Acredito que isso deva ser criado na conta ou na organização do react brasil. 

Então, o que me sugerem fazer?

**Comment by rodrigooler** [comment]
@jvcjunior acredito que seja melhor ver com o @danvitoriano.

**Comment by danvitoriano** [comment]
veja se vc já consegue ter acesso aos webhooks @jvcjunior

**Comment by jvcjunior** [comment]
ainda não @danvitoriano

**Comment by danvitoriano** [comment]
veja no seu email, pq eu te dei acesso ao repositório, ou veja se vc já consegue mexer nos settings
:thinking:

**Comment by jvcjunior** [comment]
consegui ver o settings agora @danvitoriano. Vou conferir essa parada do 404 e da conta. 

Obrigado! ;)

**Comment by danvitoriano** [comment]
maravilha @jvcjunior! resolveu? qquer duvida manda ae!

**Comment by jvcjunior** [comment]
Cara.. consigo fazer deploy de boas via minha máquina local. É tanto que gerei aquele link com o site já feito deploy. Não consegui identificar ainda porque nos hooks está dando 404. Isso é o que estou investigando agora. Vi que não está dando para fazer o deploy via o site do stage, tem até uma issue no github.

**Comment by danvitoriano** [comment]
putz! talvez a solução esteja bugada! alguém conhece outra opção?

**Comment by jvcjunior** [comment]
Vou continuar vendo isso pra ver se passou algo despercebido. Mas num deveria ser complicado não, talvez alguma coisa não estava 100%. Vou ver  o que acho. o/

**Comment by danvitoriano** [comment]
eu tb não entendi mano, pergunta no grupo do Slack!

**Comment by jvcjunior** [comment]
Criei uma issue lá no repositório do stage pra ver se a galera me ajuda com isso.

**Comment by danvitoriano** [comment]
Aonde você criou essa issue @jvcjunior ? Eu não achei. O repo da conf é esse não?

**Comment by jvcjunior** [comment]
Não, no repo do stage mesmo: https://github.com/zpnk/stage-ci/issues/19

**Comment by danvitoriano** [comment]
opa! entendi! foi mal @jvcjunior

**Comment by valterjuniorifactory** [comment]
é.. tem outro carinha que falou lá na issue estar enfrentando o mesmo problema, acho que num vai rolar o now agora não. Pelo menos por enquanto. 

Alguém teria alguma outra sugestão? @danvitoriano o que acha?

**Comment by danvitoriano** [comment]
vou postar no slack @valterjuniorifactory

**Comment by jvcjunior** [comment]
Achei esse cara @danvitoriano : https://surge.sh/

Vou conferir se dá pra fazer o que queremos! Abraço!

**Comment by jvcjunior** [comment]
@danvitoriano, o carinha lá do repositório me respondeu e pediu pra tentar de novo de outra forma. Eu tentei e podemos dizer que funcionou em parte. Porque o link que ele(now) gerou foi esse: 
`https://stage-ci-wfwyzjcrad.now.sh/`

Se notar, parece estar meio bugado. Estou tentando descobrir o porque. Mas queria que você fizesse algo para testar o webhook. Talvez colocar uma label em um pull request, ou abrir um fake, ou reabrir um. Acho que esses eventos vão fazer o webhook rodar. Poderia fazer isso?

**Comment by jvcjunior** [comment]
@danvitoriano agora acho que foi. Consegui configurar e executar uma vez o webhook e gerar uma versão. Poderia dar uma conferida e analisar se falta algo. Obrigado!

**Comment by danvitoriano** [comment]
oi @jvcjunior desculpa cara! correria aqui com varias coisas pra fazer e eu nem consegui abrir a PR pra gente testar!
vou testar entao e te aviso, mas se vc ta falando q foi, eh pq foi! hehehe
muito obrigado cara!

**Comment by jvcjunior** [comment]
Massa @danvitoriano. Caso não esteja como deseja ou precise mudar algo, por favor me avisa que eu dou uma conferida!

**Comment by rodrigooler** [comment]
@danvitoriano conseguiu testar o stage now ?

**Comment by danvitoriano** [comment]
não testei @rodrigooler podiamos testar o staging com esse deploy e ai fechamos esta issue
