### ISSUE TITLE
Anunciar palestrantes: Pedro, Bruno, Guilherme, Rafael 🎉

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#123]
Nome: Pedro Nauck
Local: Florianópolis, SC
Empresa: Docz https://www.docz.site/
Foto: 
![pedro nauck](https://user-images.githubusercontent.com/66042/45792692-4cbd6700-bc65-11e8-976e-75b7de44a875.jpg)
Tema: Docz: de 0 a 5.000 ⭐️ em 2 semanas
Link: https://www.youtube.com/watch?v=NqcEZZqZ7xQ

Nome: Bruno da Hora
Local: Curitiba, PR
Empresa: Pipefy https://www.pipefy.com/
Foto: 
![bruno_da_hora](https://user-images.githubusercontent.com/66042/45792824-d2d9ad80-bc65-11e8-8040-71a82b5edaa2.jpg)
Tema: Otimize seu bundle com Webpack 4 e Create React App
Link: https://www.youtube.com/watch?v=Hg_e7LX3VZo

Nome: Guilherme Varandas
Local: Brasília, DF
Empresa: Banco do Brasil https://www.bb.com.br
Foto: 
![guilherme_varandas](https://user-images.githubusercontent.com/66042/45792988-7460ff00-bc66-11e8-930e-509607bbd279.jpg)
Tema: React Native no Banco do Brasil: Como RN nós faz poupar 1500 horas por projeto
Link: https://www.youtube.com/watch?v=5KL-6FkJvMw

Nome: Raphael Porto
Local: Rio de Janeiro, RJ
Empresa: Globo.com https://www.globo.com
Foto: 
![rafael_porto](https://user-images.githubusercontent.com/66042/45793158-226ca900-bc67-11e8-907e-de1c3ef0904f.jpg)
Tema: A Jornada do React Native na Globo.com
Link: https://www.youtube.com/watch?v=L16Wp-dS-HY

**Comment by danielGalvao** [comment]
Done!
