### ISSUE TITLE
Anunciar palestrante: Raphael Amorim 🎉

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#124]
Nome: Raphael Amorim
Local: Rio de Janeiro, RJ
Empresa: GoDaddy https://godaddy.com
Rede Social: https://twitter.com/raphamorims / https://github.com/raphamorim
Vídeo: https://youtu.be/ADFHQ-I9Scg
Talk: Escrevendo seu próprio React Render
Foto: 
![42202097_692760551095628_8236164097243086848_n](https://user-images.githubusercontent.com/66042/45895230-ffe1a980-bda6-11e8-873f-95b896928301.jpg)

**Comment by danielGalvao** [comment]
Done!
