### ISSUE TITLE
Anunciar palestrante: Maira Bello 🎉

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#126]
Nome: Maira Bello
Local: Recife, PE
Empresa: In Loco https://www.inlocomedia.com
Github: https://github.com/mairatma
Vídeo: https://youtu.be/zQG2uL-KUtg
Talk: Escalando o GraphQL
Foto: 
![maira](https://user-images.githubusercontent.com/66042/46037440-7ac7fe80-c0de-11e8-8e47-b621377d8d51.jpg)

**Comment by danielGalvao** [comment]
Done!
