### ISSUE TITLE
Anunciar palestrante: da2k e sibelius 🎉

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#127]
Nome: Fernando Daciuk
Local: Curitiba, PR
Empresa: Zimp  https://zimp.me
Github: https://github.com/fdaciuk
Vídeo https://youtu.be/ZHpVZYnGx6s
Talk: O poder do SSR
Foto: 
![22366401_285262001991484_4021619538695388972_n](https://user-images.githubusercontent.com/66042/46449532-d93a5000-c762-11e8-8aa3-2827318da610.jpg)

---

Nome: Sibelius Seraphini
Local: São Paulo, SP
Empresa: Feedback House  https://feedback.house/
Github: https://github.com/sibelius
Vídeo https://youtu.be/4YjT7-ZcDtI
Talk: Deferred rendering e fetching com GraphQL e React
Foto:
![22519602_287657498418601_8518975789318580727_n](https://user-images.githubusercontent.com/66042/46449529-d5a6c900-c762-11e8-8d2b-fb81d975e367.jpg)

**Comment by danielGalvao** [comment]
Done!
