### ISSUE TITLE
Anunciar Matheus Marsiglio 🎉

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#128]
Nome: Matheus Marsiglio
Local: São Paulo, SP
Empresa: 
Github: https://github.com/mtmr0x
Vídeo: https://youtu.be/jzW2WEzW0U8
Talk: Meu próprio conjunto de regras para viver uma vida longa com state containers
Foto: 
![img_2662](https://user-images.githubusercontent.com/66042/46556052-c8e9b880-c8bb-11e8-9851-b34119b80ec6.JPG)

**Comment by danielGalvao** [comment]
Mais que vídeo é esse!!! Kkkkkk 1991 mesmo!

**Comment by danielGalvao** [comment]
@mtmr0x O tema da palrastes deveria ser “Irene de volta para o futuro”

**Comment by nic** [comment]
Ele não viu ainda.. Hahahahahaha

**Comment by nic** [comment]
Só um toque de... a e s t h e t i c s

![vaporwave_aesthetic_by_rafael_de_jongh-db6uwhg](https://user-images.githubusercontent.com/66042/46557468-562f0c00-c8c0-11e8-93b1-9d26d4d5f8ca.jpg)

**Comment by mtmr0x** [comment]
@nic @danielGalvao só deixa em branco a parte da empresa. Sigo forte com minha politica de desassociação de qualquer empresa.
