### ISSUE TITLE
Adicionar link do Call 4 Papers no fotter do site da Conf

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#13]
Adicionar na página seção com link para a página de Call For Papers:
<https://www.papercall.io/reactconfbr>

**Comment by rodrigooler** [comment]
Issue finalizada https://github.com/react-brasil/conf/pull/20

**Comment by danvitoriano** [comment]
Galera, voces vao me achar mala se eu reabrir essa issue?
Pq nao basta alterar o `src`, tem que gerar o build para a pasta `public`, compilado e minificado, senão não aparece no ar :/

**Comment by sibelius** [comment]
temos como automatizar isso?

**Comment by rodrigooler** [comment]
@danvitoriano podemos automatizar isso e documentar para que nas próximas PR.

**Comment by danvitoriano** [comment]
esta documentado @rodrigooler : 
https://github.com/react-brasil/conf , ta no readme! parte de deploy!

**Comment by brunogenaro** [comment]
Me desculpem. 
Acabei de rodar `yarn build` e `yarn deploy`.  Qual seria o próximo passo?

**Comment by brunogenaro** [comment]
Recebi este e-mail do GitHub:

> The  page build completed successfully, but returned the following warning for the `gh-pages` branch:

> The CNAME `reactconfbr.com.br` is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.

> Forinformation on troubleshooting Jekyll see:https://help.github.com/articles/troubleshooting-jekyll-builds

> If you have any questions you can contact us by replying to this email.

**Comment by danvitoriano** [comment]
deixa eu verificar o que esta rolando @brunogenaro

**Comment by rodrigooler** [comment]
Atualizando @danvitoriano 
<img width="1195" alt="screen shot 2017-06-13 at 14 18 01" src="https://user-images.githubusercontent.com/5496931/27095176-2e859ce2-5043-11e7-86ba-7f03dc0984d2.png">

**Comment by danvitoriano** [comment]
Valeu! Obrigado @rodrigooler e @brunogenaro !
Alias, @brunogenaro nao consegui ver pq deu esse erro na hora de gerar o yarn deploy, mas o @rodrigooler colocou uns hooks que ao buildar a master vai gerar a gh-pages agora!
