### ISSUE TITLE
Adicionar css loader

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#14]
Para evitar o blink da página ao carregar, o @sebas5384 sugeriu adicionar o CSS LOADER no wepack ou algo similar.

Sugestão:
https://danilowoz.github.io/react-content-loader/

**Comment by lucasbento** [comment]
Não tem outro jeito de trabalhar isso?

Hoje nem usamos `.css` files, só glamor.

cc @ronal2do.

**Comment by ronal2do** [comment]
Cara vou resolver isso agora.

**Comment by ronal2do** [comment]
e adicionar a section de ajuda

**Comment by danvitoriano** [comment]
você vai ver essa aqui tb @ronal2do senão podíamos compartilhar no face e alguém dar um assing

**Comment by jvcjunior** [comment]
Alguma novidade sobre essa daqui @danvitoriano? Talvez eu pudesse pegar ela...
