### ISSUE TITLE
Adicionar área para ajudar o Leo Konarzewski a vencer o câncer

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#15]
Como muitos sabem, o desenvolvedor Leo Konarzewski há anos vem lutando com o câncer.

Toda a comunidade está envolvida em arrecadar fundos para o seu tratamento no Exterior.

Precisamos adicionar uma chamada ao menos para a página no Facebook:

https://www.facebook.com/groups/ajudeleokz/

**Comment by rodrigooler** [comment]
Alguma ideia de qual lugar é melhor para colocar essa informação?

**Comment by danvitoriano** [comment]
pode ser a última seção do site, antes do footer @rodrigooler 
o que acha da ideia?

**Comment by ronal2do** [comment]
Apoio

**Comment by danvitoriano** [comment]
Quem for fazer, por favor, dá um assign na issue, pra gente saber que ela já tem dono ;)
