### ISSUE TITLE
Adicionar HandTalk.me

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#25]
Transforma textos em libras. 
https://handtalk.me/

**Comment by ronal2do** [comment]
Posso buscar um apoio deles

**Comment by ronal2do** [comment]
retorno até terça feira (20 de Junho)

**Comment by vinirossi** [comment]
Ainda não sei como usar o github, mas acho que a mensagem é por aqui. Achei esse que é gratuito no plano bem básico http://www.weblibras.com.br/

**Comment by danvitoriano** [comment]
tks @vinirossi, good help link!

**Comment by danvitoriano** [comment]
any progress @ronal2do with sponsorship? 
otherwise, unassign this issue and let someone to code this weblibras free option plan
I can register it

**Comment by ronal2do** [comment]
Today night Im send media-kit

**Comment by danvitoriano** [comment]
any progress @ronal2do ?

**Comment by danvitoriano** [comment]
I tested #62 and it breaks when the box is open
