### ISSUE TITLE
Melhorar Call For Paper link no site

### ISSUE THREAD

**Issue by sibelius** [react-brasil/conf#29]
![image](https://user-images.githubusercontent.com/2005841/27735770-9e945762-5d77-11e7-8e64-e22e39e33c3f.png)

Vierem me perguntar como faz para enviar um Call For Papers para o React Conf BR

Acho que temos que melhorar nosso site para deixar essa informações mais fácil

**Comment by ronal2do** [comment]
Boa vou encontrar o DA agora é incluir esse pedacinho

**Comment by danvitoriano** [comment]
Ficou um pouco escondido
