### ISSUE TITLE
Problema na lista de papers e votação via github

### ISSUE THREAD

**Issue by teonimesic** [react-brasil/conf#33]
Dúvida, no site do react conf tem uns números de `votação pelo github`… Mas não achei onde vota! Proponho que os cards das propostas sejam:

1 - Links pra talk em si com possibilidade de votar
2 - Dinâmicos contendo a quantidade real de votos de cada coisa

Se precisar de ajudar pra implementar isso ai só me falar que eu faço, só preciso saber onde estão as talks em si e o mecanismo de votação pra criar um crawler

**Comment by danvitoriano** [comment]
o q vc pode fazer tb, é trazer os topicos dessa issue https://github.com/react-brasil/reactconfbr/issues/8 pra dentro do site e deixar que as pessoas continuarem votando ;)

**Comment by sibelius** [comment]
podemos usar isso daqui https://github.com/tj/gh-polls

**Comment by danvitoriano** [comment]
vamos por partes:

1 - não acho possível abrirmos as talks para votação pública. já viu muito evento antes fazendo isso, e o cara dono da talk chamava a mãe, a vizinha, o papagaio pra votar na talk dele, e os organizadores do evento se viam obrigado a chamar alguém para palestrar q na verdade ganhou só pq fez campanha, mas que o interesse da comunidade pelo tema era nulo. Sendo assim, nós já temos uma comissão responsável por analisar os call for papers que estão chegando. estas pessoas são bastante ativas no nosso slack, atuam nos meetups em sp e em floripa e possuem capacidade e discernimento para eleger as palestras mais interessantes, até pq, se escolhermos palestras ruins, nao venderemos ingressos e consequentemente, precisamos pagar para q o evento aconteça, não correndo o lucro de termos prejuízo. Além do mais, escolher os palestrantes envolve toda uma logística, pois a pessoa é abordada, questionada sobre o paper enviado, chegamos a viabilidade de trazê-la para a conf, seu transporte, sua hospedagem, sua alimentação, vistos, documentação, e para tudo isso, é preciso saber se a grana que temos nos permite trazê-la. enfim, infelizmente, não dá pra ser muito democrático nesse item, por isso, nossa comissão de C4P vai garantir que as melhores talks serão parte da programação.

2 - isso sim pode ser feito, trazer diretamente os itens já listados na issue https://github.com/react-brasil/reactconfbr/issues/8 para dentro do nosso site e permitir que as pessoas continuem votando. é só fazer um fork do repo, criar esta integração e enviar uma Pull Request

vou fechar esta issue, e se acharem que vale a pena, abram outra issue com este item 2 sozinho.
vlw, paz
