### ISSUE TITLE
Traduzir o site para inglês e espanhol

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#35]
usando i18n

**Comment by danvitoriano** [comment]
https://braziljs.org/blog/implementando-internacionalizacao-i18n-com-javascript/

**Comment by matheusmonte** [comment]
Posso fazer essa task?

**Comment by ronal2do** [comment]
@matheusmonte  com maior prazer cara, só mandar seu PR

**Comment by matheusmonte** [comment]
Show, a caminho

**Comment by ronal2do** [comment]
tente colocar nesse Branch 

https://github.com/react-brasil/conf/tree/feature/layout

**Comment by danvitoriano** [comment]
manda ver @matheusmonte !

**Comment by gabrielferreiraa** [comment]
@matheusmonte, está dando certo a task ? :smiley:

**Comment by matheusmonte** [comment]
Fala galera, tá em progress, mas mudaram alguns prazos aqui no meu trabalho e estou trabalhando em uma entrega grande dia e noite, fecho sexta feira, vou poder voltar a trabalhar no fimd e semana na issue

**Comment by gabrielferreiraa** [comment]
Show :D Só pra gente saber o status da issue. Valeu bro

**Comment by sibelius** [comment]
@gabrielferreiraa alinha com o @matheusmonte para vcs trabalharem nisso em conjunto

o screenhero é legal para pair programming

**Comment by gabrielferreiraa** [comment]
@matheusmonte entra (se você não estiver) no slack do [React Brasil](https://react-brasil.slack.com) e me manda um direct. Vamos trabalhar juntos nessa task ! :D

**Comment by matheusmonte** [comment]
Te pingo lá a noite

**Comment by danvitoriano** [comment]
@matheusmonte e @gabrielferreiraa depois falem comigo para alinharmos estes textos, estamos mexendo na versão nova, várias áreas vão sair e coisas novas vão entrar ;)

**Comment by danvitoriano** [comment]
hey @gabrielferreiraa e @matheusmonte o novo site está todo em portugues, mas se vc abrir no chrome ele pede pra ser traduzido. a versão inglês tá lisa... mudamos um pouco o portugues para q só na traducao automatica ele ja ficasse multilanguage, entao se quiserem usar isso pra ver os outros idiomais, acho q já facilita!

**Comment by gabrielferreiraa** [comment]
@matheusmonte estou te chamando no slack para você me passar o que foi feito e como vamos trabalhar de agora em diante.

**Comment by danvitoriano** [comment]
trying to apply this as quickly option:
https://translate.google.com/manager/website/?hl=yi

**Comment by danvitoriano** [comment]
solved partially with #79
