### ISSUE TITLE
Problema com imagem tampando a data do evento

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#37]
![captura de tela 2017-07-20 as 17 36 33](https://user-images.githubusercontent.com/66042/28437738-23dc2de6-6d72-11e7-85b8-8683856614a4.png)

Versão responsiva:
![captura de tela 2017-07-20 as 17 45 12](https://user-images.githubusercontent.com/66042/28438048-32e9d6fc-6d73-11e7-94fe-b1dbc02f2868.png)

**Comment by ronal2do** [comment]
Eu parei para vir para casa acho que não era para dar merge.

**Comment by danvitoriano** [comment]
fizemos o deploy da versao anterior
