### ISSUE TITLE
Adicionar descrição da palestra do Fernando Daciuk

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#48]
O nome da palestra é: "The magic world of tests with Jest"

Como está:
![captura de tela 2017-08-04 as 00 03 17](https://user-images.githubusercontent.com/66042/28952557-56194a3c-78a8-11e7-91e7-bd8fbe0b7c6d.png)

Como deverá ficar:
![captura de tela 2017-08-04 as 00 03 59](https://user-images.githubusercontent.com/66042/28952580-720dd942-78a8-11e7-9eb3-02501190b2f5.png)

**Comment by gabrielferreiraa** [comment]
@rodrigooler posso alterar via PR ? Ou vamos aguardar um pouco para alterar ?

**Comment by sibelius** [comment]
pode mandar

**Comment by sibelius** [comment]
done
