### ISSUE TITLE
Atualizar botão de ingressos

### ISSUE THREAD

**Issue by gabrielferreiraa** [react-brasil/conf#49]
Terceiro lote de ingressos já foi aberto porém o botão no site está:
![btn](https://user-images.githubusercontent.com/17201177/28969634-b50ea73c-78fb-11e7-91ed-0234b22df3e4.png)

**Comment by rodrigooler** [comment]
@gabrielferreiraa poderia enviar uma PR?

**Comment by gabrielferreiraa** [comment]
https://github.com/react-brasil/conf/pull/50 ta na mão

**Comment by sibelius** [comment]
done

**Comment by danvitoriano** [comment]
valeu @gabrielferreiraa
