### ISSUE TITLE
color: 'blue'; em produção

### ISSUE THREAD

**Issue by nic** [react-brasil/conf#54]
Está correta esta cor azulzão "00 00 FF"?

![captura de tela 2017-08-21 as 10 02 05](https://user-images.githubusercontent.com/66042/29520555-eaa56a8e-8657-11e7-9bcc-1f15a8bad42f.png)

**Comment by fdaciuk** [comment]
Talvez um `#00a9ff`, que fica mais próximo do azul claro e dá um contraste legal em fundo claro =)

**Comment by gabrielferreiraa** [comment]
Boa @fdaciuk, `#00a9ff` ficou muito bom!

**Comment by fdaciuk** [comment]
Mandei PR em #55 :)

**Comment by fdaciuk** [comment]
Dei uma escurecida no cinza e amarelo também, e troquei a cor do texto do botão de C4P para branco, como está no fundo branco achei que deu uma melhorada no contraste. Se não ficou bom eu mudo aqui :)
