### ISSUE TITLE
Barra de rolagem horizontal

### ISSUE THREAD

**Issue by fdaciuk** [react-brasil/conf#72]
Está aparecendo uma barra de rolagem horizontal na página:

![screenshot from 2017-09-14 09-12-11](https://user-images.githubusercontent.com/487669/30429179-e7172546-992c-11e7-895e-134d684c8f21.png)

**Comment by sebas5384** [comment]
@fdaciuk opa! qual é o browser?

**Comment by danvitoriano** [comment]
qual o navegador @fdaciuk e a resolução? valeu!

**Comment by fdaciuk** [comment]
Chrome no Linux, qualquer resolução xD
A que estou usando é 1366x768, mas abaixo disso também fica a rolagem =)

**Comment by danvitoriano** [comment]
deve ser alguma coisa com o video em background, mas no meu nao aparece, vou tentar browser stack. vc usa ubuntu né? @fdaciuk

**Comment by danvitoriano** [comment]
`overflowX: 'hidden' `solve this

**Comment by fdaciuk** [comment]
Isso! Vou testar aqui @danvitoriano =)

**Comment by danvitoriano** [comment]
check it on [production](http://reactconfbr.com.br) @fdaciuk pls

**Comment by fdaciuk** [comment]
It's nice =)
