### ISSUE TITLE
Add title talk Keuller Magalhães

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#82]
Title: `React Performance from Scratch`

**Comment by MathMesquita** [comment]
I can take this one :)

**Comment by danvitoriano** [comment]
can you assign to you this issue @MathMesquita ?

**Comment by MathMesquita** [comment]
I need write permission to do it myself @danvitoriano

**Comment by danvitoriano** [comment]
it should be on your mail @MathMesquita !

**Comment by danvitoriano** [comment]
done!
