### ISSUE TITLE
Add João Gonçalves as Speaker

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#83]
Name: João Gonçalves
From: Campinas, Brasil
Company: [Movile](https://www.movile.com/)
Talk Title: Show do Milhão React PWA (Caso de Sucesso)
Avatar: https://drive.google.com/file/d/0Bxl-8_oWXUXXMEozRXNaRldmU3c/view?usp=sharing

**Comment by MathMesquita** [comment]
Could you assign this one also to me? I'm already doing #82 and the changes must be done in the same file.

**Comment by MathMesquita** [comment]
It's missing his github profile btw

**Comment by danvitoriano** [comment]
done!
