### ISSUE TITLE
Add www to Pipefy Url

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/conf#88]
Add `www` where https://pipefy.com, to https://www.pipefy.com

### Components: 
[src/components/Sponsor.js](https://github.com/react-brasil/conf/blob/master/src/components/Sponsor.js)
[src/components/Speakers.js](https://github.com/react-brasil/conf/blob/master/src/components/Speakers.js)

**Comment by MathMesquita** [comment]
let's merge #89 to solve this one ! :)

**Comment by danvitoriano** [comment]
done with #90
